### ISSUE TITLE
Blog: scrollbar-* utility for Tailwind CSS v4

### ISSUE THREAD

**Issue by rozsazoltan** [rozsazoltan/rozsazoltan.vercel.app#32]
> I've used this code [&::-webkit-scrollbar-track] [&::-webkit-scrollbar-thumb] etc but it's not working for firefox

> Not supported: [`css.selectors.-webkit-scrollbar-*`](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar#css.selectors.-webkit-scrollbar-track)
>
> I simply don't bother with the scrollbar in Firefox, but there are alternatives: [Custom CSS Scrollbar for Firefox](https://stackoverflow.com/q/6165472/15167500)

> It seems like scrollbar-color: <thumb> <track> works in firefox. Didn't have much luck with a custom utility to concat(?) the two colors but something like [scrollbar-color:#f00_#000] works.
> I don't know the trick to do var(--thumb-color) var(--track-color) with CSS, gave it a shot here. For whatever reason it's ignoring the track color: https://play.tailwindcss.com/eccf9eBaIz?file=css

> Can do something like this https://play.tailwindcss.com/rmqiF15Bjo?file=css  (works in Firefox)

> This won’t work well [in Safari](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color#browser_compatibility). I hate these compatibility issues. So maybe: https://play.tailwindcss.com/hqLmbTHBde?file=css (works in everywhere)

> Here it is with the properties switched right and a proper fallback since falling back to auto when one isn't defined causes issues: https://play.tailwindcss.com/YSTSwsspBH?file=css

* Source: crswll, Robin, me (from Discord general room)

**Comment by rozsazoltan** [comment]
```css
@import "tailwindcss";

@utility scrollbar-track-* {
  --scrollbar-track-color: --value(--color);

  @supports (scrollbar-color: red blue) {
    scrollbar-color: var(--scrollbar-thumb-color, black) var(--scrollbar-track-color);
  }

  @supports not (scrollbar-color: red blue) {
    &::-webkit-scrollbar-track {
      background-color: var(--scrollbar-track-color);
    }
  }
}

@utility scrollbar-thumb-* {
  --scrollbar-thumb-color: --value(--color);

  @supports (scrollbar-color: red blue) {
    scrollbar-color: var(--scrollbar-thumb-color) var(--scrollbar-track-color, transparent);
  }

  @supports not (scrollbar-color: red blue) {
    &::-webkit-scrollbar-thumb {
      background-color: var(--scrollbar-thumb-color);
    }
  }
}
```
